version: v1

lookback_hours: 24

keywords:
  - hack
  - exploit
  - outage
  - halted
  - suspended
  - breach
  - sec
  - regulation
  - lawsuit
  - etf
  - ban
  - fine

sources:
  - type: telegram
    channels:
      - "@binance_announcements"
      - "@cointelegraph"
      - "@whale_alert"
      - "@coinbase"
    limit_per_channel: 200

  - type: web
    sites:
      - "https://3dnews.ru"

limits:
  max_items: 7
